### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by biostars-nyc** [cgplab/Rockermeth#6]
### I get the following output + errors when attempting to install via dev tools:

ownloading GitHub repo cgplab/Rockermeth@HEAD
Skipping 3 packages not available: IRanges, GenomicRanges, S4Vectors
✓  checking for file ‘/private/var/folders/2w/dgzchz7j45sbkqfppwffx2gr0000gq/T/RtmpyoRRoX/remotes11f81c729d90/cgplab-Rockermeth-15dfe35/DESCRIPTION’ (894ms)
─  preparing ‘Rockermeth’: (505ms)
✓  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Rockermeth_0.1.0.tar.gz’
   
* installing *source* package ‘Rockermeth’ ...
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c MethLibrary.f -o MethLibrary.o
MethLibrary.f:8:40:

    8 |        DOUBLE PRECISION NDELTA(KTILDE,T),PDELTA(KTILDE,T)
      |                                        1
Warning: Unused variable 'ndelta' declared at (1) [-Wunused-variable]
MethLibrary.f:5:28:

    5 |        DOUBLE PRECISION NORM,NORM1,NUMMAX
      |                            1
Warning: Unused variable 'norm' declared at (1) [-Wunused-variable]
MethLibrary.f:5:34:

    5 |        DOUBLE PRECISION NORM,NORM1,NUMMAX
      |                                  1
Warning: Unused variable 'norm1' declared at (1) [-Wunused-variable]
MethLibrary.f:8:57:

    8 |        DOUBLE PRECISION NDELTA(KTILDE,T),PDELTA(KTILDE,T)
      |                                                         1
Warning: Unused variable 'pdelta' declared at (1) [-Wunused-variable]
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Rockermeth.so MethLibrary.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Rockermeth.so] Error 1
ERROR: compilation failed for package ‘Rockermeth’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rockermeth’
Warning message:
In i.p(...) :
  installation of package '/var/folders/2w/dgzchz7j45sbkqfppwffx2gr0000gq/T//RtmpyoRRoX/file11f828c66787/Rockermeth_0.1.0.tar.gz' had non-zero exit status

**Comment by romagnolid** [comment]
Hi @biostars-nyc, it looks like an issue related to the Mac environment. I don't know your expertise so forgive me if I suggest something obvious. First of all you you need to install Xcode. Second, I found this related issue on [stackexchange](https://stackoverflow.com/questions/58610155/problem-installing-r-package-ld-warning-directory-not-found-for-option) 
which redirects to [this guide](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) to install R compiler tools on MacOS.

**Comment by biostars-nyc** [comment]
Thanks I was able to resolve it!
